#ifndef BLIZZARD_COLORS_H
#define BLIZZARD_COLORS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct color_t{
    uint8_t red;
    uint8_t green;
    uint8_t blue;
}__attribute__((packed)) color_t;

typedef union color32_t
{
    color_t _color;
    uint32_t val;
}__attribute__((packed)) color32_t;


// typedef struct color32_t{
//   union {
//     struct {
//       color_t _color;
//       uint8_t _padding;
//     };
//     uint32_t val;
//   } _color;
// }__attribute__((packed)) color32_t;

// typedef 
 

#define DONT_CARE_COLOR ((color_t){0, 0, 0})

#define BLIZZARD_BLINDER ((color_t){255, 255, 255})
#define BLIZZARD_ERROR ((color_t){255, 0, 0})
#define BLIZZARD_DATA_COLOR ((color_t){13,13,13})
#define BLIZZARD_BATTERY_COLOR ((color_t){34,8,0})
#define BLIZZARD_BRIGHT_WHITE ((color_t) {144, 144, 144})
#define BLIZZARD_BRIGHT_RED ((color_t) {255,0,0})
#define BLIZZARD_BRIGHT_GREEN ((color_t) {0,255,0})

#define BLIZZARD_RED ((color_t){55, 0, 0})
#define BLIZZARD_ORANGE ((color_t){55, 14, 0})
#define BLIZZARD_YELLOW ((color_t){55, 46, 0})
#define BLIZZARD_GREEN ((color_t){0, 55, 0})
#define BLIZZARD_BLUE ((color_t){0, 0, 55})
#define BLIZZARD_PURPLE ((color_t){35,0,55})
#define BLIZZARD_WHITE ((color_t){55, 55, 55})
#define BLIZZARD_BLACK ((color_t){0, 0, 0})
#define BLIZZARD_GREY ((color_t){21, 21, 21})

#define BLIZZARD_DIM_RED ((color_t){25, 0, 0})
#define BLIZZARD_DIM_ORANGE ((color_t){25, 7, 0})
#define BLIZZARD_DIM_YELLOW ((color_t){25, 23, 0})
#define BLIZZARD_DIM_GREEN ((color_t){0, 25, 0})
#define BLIZZARD_DIM_BLUE ((color_t){0, 0, 25})
#define BLIZZARD_DIM_PURPLE ((color_t){17, 0, 25})
#define BLIZZARD_DIM_WHITE ((color_t){25, 25, 25})
#define BLIZZARD_DIM_BLACK ((color_t){0, 0, 0})
#define BLIZZARD_DIM_GREY ((color_t){10, 10, 10})
#define BLIZZARD_DIM_ERROR ((color_t){100, 0, 0})

#define BLIZZARD_ULTRA_DIM_RED ((color_t){13, 0, 0})

#define LIME ((color_t){50,255,50})
#define ORCHID ((color_t){218,20,20})
#define VIOLET ((color_t){255,20,255})
#define EGGSHELL ((color_t){240,234,214})

#define ANIMATION_BREATH_SLOW 0
#define ANIMATION_BREATH 1
#define ANIMATION_BREATH_FAST 2

#define ANIMATION_BLINK_SLOW 3
#define ANIMATION_BLINK 4
#define ANIMATION_BLINK_FAST 5

#define ANIMATION_SOLID 6

#define ANIMATION_DIT_5 7
#define ANIMATION_DIT_4 8
#define ANIMATION_DIT_3 9
#define ANIMATION_DIT_2 10
#define ANIMATION_DIT_1 11

#define ANIMATION_BATTERY_CRIT 12

#define ANIMATION_RAINBOW 13
#define ANIMATION_S1 14
#define ANIMATION_S2 15
#define ANIMATION_S3 16

#define ANIMATION_QC_CONNECTING 20
#define ANIMATION_QC_CONNECTED 21

#define UI_STOP_COLOR BLIZZARD_BRIGHT_RED
#define UI_PLAY_COLOR BLIZZARD_BRIGHT_GREEN

#define UI_FORWARD_COLOR BLIZZARD_GREY
#define UI_REVERSE_COLOR BLIZZARD_GREY

#define UI_IDLE_STATE_WIFI_EZ_CONNECTING_COLOR BLIZZARD_DIM_GREEN
#define UI_IDLE_STATE_WIFI_EZ_CONNECTING_ANIMATION ANIMATION_BLINK_FAST

#define UI_IDLE_STATE_WIFI_CONNECTING_COLOR BLIZZARD_DIM_GREEN
#define UI_IDLE_STATE_WIFI_CONNECTING_ANIMATION ANIMATION_BREATH_FAST

#define UI_IDLE_STATE_WIFI_CONNECTED_COLOR BLIZZARD_DIM_GREEN
#define UI_IDLE_STATE_WIFI_CONNECTED_ANIMATION ANIMATION_SOLID

#define UI_IDLE_STATE_WIFI_ERROR_BAD_PASS_COLOR BLIZZARD_DIM_YELLOW
#define UI_IDLE_STATE_WIFI_ERROR_BAD_PASS_ANIMATION ANIMATION_DIT_3

#define UI_IDLE_STATE_WIFI_ERROR_BAD_SSID_COLOR BLIZZARD_DIM_YELLOW
#define UI_IDLE_STATE_WIFI_ERROR_BAD_SSID_ANIMATION ANIMATION_DIT_2

#define UI_IDLE_STATE_WIFI_ERROR_BAD_WIFI_COLOR BLIZZARD_DIM_YELLOW
#define UI_IDLE_STATE_WIFI_ERROR_BAD_WIFI_ANIMATION ANIMATION_BLINK_FAST

#define UI_IDLE_STATE_AP_IDLE_COLOR BLIZZARD_DIM_BLUE
#define UI_IDLE_STATE_AP_IDLE_ANIMATION ANIMATION_BLINK_SLOW

#define UI_IDLE_STATE_AP_DEVICE_CONNECTED_COLOR BLIZZARD_DIM_BLUE
#define UI_IDLE_STATE_AP_DEVICE_CONNECTED_ANIMATION ANIMATION_SOLID

#define UI_IDLE_STATE_MUTE_COLOR BLIZZARD_BLACK
#define UI_IDLE_STATE_MUTE_ANIMATION ANIMATION_SOLID

#define UI_IDLE_STATE_LOCATE_COLOR BLIZZARD_BLINDER
#define UI_IDLE_STATE_LOCATE_ANIMATION ANIMATION_BLINK_FAST

#define UI_BATTERY_STATE_LEVEL_CRIT_COLOR BLIZZARD_DIM_RED
#define UI_BATTERY_STATE_LEVEL_CRIT_ANIMATION ANIMATION_BATTERY_CRIT

#define UI_BATTERY_STATE_LEVEL_5_COLOR BLIZZARD_DIM_RED
#define UI_BATTERY_STATE_LEVEL_5_ANIMATION ANIMATION_DIT_5

#define UI_BATTERY_STATE_LEVEL_4_COLOR BLIZZARD_DIM_RED
#define UI_BATTERY_STATE_LEVEL_4_ANIMATION ANIMATION_DIT_4

#define UI_BATTERY_STATE_LEVEL_3_COLOR BLIZZARD_DIM_RED
#define UI_BATTERY_STATE_LEVEL_3_ANIMATION ANIMATION_DIT_3

#define UI_BATTERY_STATE_LEVEL_2_COLOR BLIZZARD_DIM_RED
#define UI_BATTERY_STATE_LEVEL_2_ANIMATION ANIMATION_DIT_2

#define UI_BATTERY_STATE_LEVEL_1_COLOR BLIZZARD_DIM_RED
#define UI_BATTERY_STATE_LEVEL_1_ANIMATION ANIMATION_DIT_1

#define UI_BATTERY_STATE_CHARGING_COLOR BLIZZARD_DIM_RED
#define UI_BATTERY_STATE_CHARGING_ANIMATION ANIMATION_BREATH

#define UI_BATTERY_STATE_DONE_CHARGING_COLOR BLIZZARD_DIM_RED
#define UI_BATTERY_STATE_DONE_CHARGING_ANIMATION ANIMATION_SOLID

#define UI_USER_STATE_UNDEFINED_COLOR BLIZZARD_DIM_PURPLE
#define UI_USER_STATE_UNDEFINED_ANIMATION ANIMATION_BLINK_FAST

#define UI_USER_STATE_RECORD_COLOR BLIZZARD_YELLOW
#define UI_USER_STATE_RECORD_ANIMATION ANIMATION_SOLID

#define UI_USER_STATE_RECORD_CONFIRM_COLOR BLIZZARD_YELLOW
#define UI_USER_STATE_RECORD_CONFIRM_ANIMATION ANIMATION_BLINK_FAST

#define UI_USER_STATE_RECORDING_COLOR BLIZZARD_RED
#define UI_USER_STATE_RECORDING_ANIMATION ANIMATION_SOLID

#define UI_USER_STATE_LISTEN_COLOR BLIZZARD_ORANGE
#define UI_USER_STATE_LISTEN_ANIMATION ANIMATION_SOLID

#define UI_USER_STATE_LISTEN_CONFIRM_COLOR BLIZZARD_ORANGE
#define UI_USER_STATE_LISTEN_CONFIRM_ANIMATION ANIMATION_BLINK_FAST

#define UI_USER_STATE_LISTENING_COLOR BLIZZARD_ORANGE
#define UI_USER_STATE_LISTENING_ANIMATION ANIMATION_BREATH

#define UI_USER_STATE_REBOOT_COLOR BLIZZARD_PURPLE
#define UI_USER_STATE_REBOOT_ANIMATION ANIMATION_SOLID

#define UI_USER_STATE_START_AP_COLOR BLIZZARD_BLUE
#define UI_USER_STATE_START_AP_ANIMATION ANIMATION_SOLID

#define UI_USER_STATE_START_AP_CONFIRM_COLOR BLIZZARD_BLUE
#define UI_USER_STATE_START_AP_CONFIRM_ANIMATION ANIMATION_BLINK_FAST

#define UI_USER_STATE_START_WIFI_COLOR BLIZZARD_GREEN
#define UI_USER_STATE_START_WIFI_ANIMATION ANIMATION_SOLID

#define UI_USER_STATE_START_WIFI_CONFIRM_COLOR BLIZZARD_GREEN
#define UI_USER_STATE_START_WIFI_CONFIRM_ANIMATION ANIMATION_BLINK_FAST

#define UI_USER_STATE_FACTORY_RESET_COLOR BLIZZARD_RED
#define UI_USER_STATE_FACTORY_RESET_ANIMATION ANIMATION_SOLID

#define UI_USER_STATE_FACTORY_RESET_CONFIRM_COLOR BLIZZARD_RED
#define UI_USER_STATE_FACTORY_RESET_CONFIRM_ANIMATION ANIMATION_BLINK_FAST

#define UI_QC_STATE_CONNECTING_COLOR BLIZZARD_BLUE
#define UI_QC_STATE_CONNECTING_ANIMATION ANIMATION_QC_CONNECTING

#define UI_QC_STATE_CONNECTED_COLOR BLIZZARD_BLUE
#define UI_QC_STATE_CONNECTED_ANIMATION ANIMATION_QC_CONNECTED

#ifdef __cplusplus
}
#endif

#endif